#!/bin/sh

module="uart.ko"
device="uart"
group="root"
mode="664"

# invoke insmod with all arguments we got
/sbin/insmod $module || exit 1

major=`cat /proc/devices | awk "\\$2==\"$device\" {print \\$1}"`

echo "Major number = $major"

rm -f /dev/${device}*
mknod /dev/uart2 c $major 0
mknod /dev/uart3 c $major 1



